"""Hermes tool-id tables and MCP-name resolution.

KEEP IN LOCKSTEP with ``HERMES_BUILTINS`` in the ai-aegis app
(``src/aegis/app/server/routes/tool_permissions.py``); the app's
``tests/unit/app/test_hermes_integration.py::test_hermes_builtins_mirror_the_sdk_table``
re-verifies the union of these three tables against its own copy.

Names are Hermes's own snake_case registry names (extracted from the
hermes-agent 0.18.0 sdist). MCP tools are NOT listed — Hermes surfaces them
as ``mcp_<server>_<tool>`` and :func:`resolve_candidates` yields the
``<server>:<tool>`` policy form alongside the raw name.
"""
from __future__ import annotations

__all__ = [
    "CORE_TOOLS",
    "BRIDGE_TOOLS",
    "BUNDLED_PLUGIN_TOOLS",
    "HERMES_BUILTINS",
    "TOOL_RISK",
    "resolve_candidates",
]

CORE_TOOLS: tuple[str, ...] = (
    "terminal",
    "process",
    "read_terminal",
    "close_terminal",
    "execute_code",
    "computer_use",
    "delegate_task",
    "cronjob",
    "read_file",
    "search_files",
    "write_file",
    "patch",
    "web_search",
    "web_extract",
    "memory",
    "session_search",
    "todo",
    "clarify",
    "skill_manage",
    "skill_view",
    "skills_list",
)

BRIDGE_TOOLS: tuple[str, ...] = (
    "tool_call",
    "tool_search",
    "tool_describe",
)

BUNDLED_PLUGIN_TOOLS: tuple[str, ...] = (
    "x_search",
    "browser_navigate",
    "browser_click",
    "browser_type",
    "browser_press",
    "browser_scroll",
    "browser_back",
    "browser_dialog",
    "browser_cdp",
    "browser_snapshot",
    "browser_console",
    "browser_get_images",
    "browser_vision",
    "vision_analyze",
    "video_analyze",
    "image_generate",
    "video_generate",
    "xai_video_edit",
    "xai_video_extend",
    "text_to_speech",
    "kanban_show",
    "kanban_list",
    "kanban_create",
    "kanban_complete",
    "kanban_block",
    "kanban_unblock",
    "kanban_comment",
    "kanban_link",
    "kanban_heartbeat",
    "project_list",
    "project_create",
    "project_switch",
    "ha_get_state",
    "ha_list_entities",
    "ha_list_services",
    "ha_call_service",
    "feishu_doc_read",
    "feishu_drive_list_comments",
    "feishu_drive_list_comment_replies",
    "feishu_drive_add_comment",
    "feishu_drive_reply_comment",
    "discord",
    "discord_admin",
    "yb_query_group_info",
    "yb_query_group_members",
    "yb_search_sticker",
    "yb_send_dm",
    "yb_send_sticker",
    "spotify_search",
    "spotify_devices",
    "spotify_playlists",
    "spotify_albums",
    "spotify_library",
    "spotify_playback",
    "spotify_queue",
    "meet_status",
    "meet_transcript",
    "meet_join",
    "meet_leave",
    "meet_say",
)

HERMES_BUILTINS: tuple[str, ...] = CORE_TOOLS + BRIDGE_TOOLS + BUNDLED_PLUGIN_TOOLS

_RISK = {
    "terminal": "admin",
    "process": "admin",
    "read_terminal": "read",
    "close_terminal": "write",
    "execute_code": "admin",
    "computer_use": "admin",
    "delegate_task": "admin",
    "cronjob": "admin",
    "tool_call": "admin",
    "tool_search": "read",
    "tool_describe": "read",
    "read_file": "read",
    "search_files": "read",
    "write_file": "write",
    "patch": "write",
    "web_search": "read",
    "web_extract": "read",
    "x_search": "read",
    "browser_navigate": "write",
    "browser_click": "write",
    "browser_type": "write",
    "browser_press": "write",
    "browser_scroll": "write",
    "browser_back": "write",
    "browser_dialog": "write",
    "browser_cdp": "admin",
    "browser_snapshot": "read",
    "browser_console": "read",
    "browser_get_images": "read",
    "browser_vision": "read",
    "vision_analyze": "read",
    "video_analyze": "read",
    "image_generate": "write",
    "video_generate": "write",
    "xai_video_edit": "write",
    "xai_video_extend": "write",
    "text_to_speech": "write",
    "memory": "write",
    "session_search": "read",
    "todo": "write",
    "clarify": "read",
    "skill_manage": "admin",
    "skill_view": "read",
    "skills_list": "read",
    "kanban_show": "read",
    "kanban_list": "read",
    "kanban_create": "write",
    "kanban_complete": "write",
    "kanban_block": "write",
    "kanban_unblock": "write",
    "kanban_comment": "write",
    "kanban_link": "write",
    "kanban_heartbeat": "write",
    "project_list": "read",
    "project_create": "write",
    "project_switch": "write",
    "ha_get_state": "read",
    "ha_list_entities": "read",
    "ha_list_services": "read",
    "ha_call_service": "admin",
    "feishu_doc_read": "read",
    "feishu_drive_list_comments": "read",
    "feishu_drive_list_comment_replies": "read",
    "feishu_drive_add_comment": "write",
    "feishu_drive_reply_comment": "write",
    "discord": "write",
    "discord_admin": "admin",
    "yb_query_group_info": "read",
    "yb_query_group_members": "read",
    "yb_search_sticker": "read",
    "yb_send_dm": "write",
    "yb_send_sticker": "write",
    "spotify_search": "read",
    "spotify_devices": "read",
    "spotify_playlists": "read",
    "spotify_albums": "read",
    "spotify_library": "read",
    "spotify_playback": "write",
    "spotify_queue": "write",
    "meet_status": "read",
    "meet_transcript": "read",
    "meet_join": "write",
    "meet_leave": "write",
    "meet_say": "write",
}
_RISK_DESC = {
    "terminal": "Run a shell command in Hermes's terminal backend.",
    "process": 'Manage background processes.',
    "read_terminal": 'Read terminal output.',
    "close_terminal": 'Close a terminal session.',
    "execute_code": "Execute generated code (not pattern-inspected by Hermes's own approval).",
    "computer_use": 'Full desktop control (screen, mouse, keyboard).',
    "delegate_task": 'Spawn a Hermes subagent.',
    "cronjob": 'Create/manage scheduled jobs (persistence).',
    "tool_call": 'Tool-Search bridge: invoke any discovered tool by name.',
    "tool_search": 'Tool-Search bridge: search the tool catalog.',
    "tool_describe": "Tool-Search bridge: describe a tool's schema.",
    "read_file": 'Read file contents.',
    "search_files": 'Search files by name/content.',
    "write_file": 'Write a file.',
    "patch": 'Apply a patch to a file.',
    "web_search": 'Search the web.',
    "web_extract": 'Fetch and extract a web page.',
    "x_search": 'Search X/Twitter.',
    "browser_navigate": 'Navigate the built-in browser.',
    "browser_click": 'Click an element in the browser.',
    "browser_type": 'Type into the browser.',
    "browser_press": 'Press a key in the browser.',
    "browser_scroll": 'Scroll the browser page.',
    "browser_back": 'Go back in browser history.',
    "browser_dialog": 'Handle a browser dialog.',
    "browser_cdp": 'Raw Chrome DevTools Protocol access.',
    "browser_snapshot": 'Snapshot the page accessibility tree.',
    "browser_console": 'Read browser console output.',
    "browser_get_images": 'Extract images from the page.',
    "browser_vision": 'Vision-analyze the current page.',
    "vision_analyze": 'Analyze an image.',
    "video_analyze": 'Analyze a video.',
    "image_generate": 'Generate an image.',
    "video_generate": 'Generate a video.',
    "xai_video_edit": 'Edit a generated video.',
    "xai_video_extend": 'Extend a generated video.',
    "text_to_speech": 'Synthesize speech audio.',
    "memory": 'Read/write Hermes long-term memory.',
    "session_search": 'Search prior Hermes sessions.',
    "todo": 'Manage the todo list.',
    "clarify": 'Ask the user a clarifying question.',
    "skill_manage": 'Install/enable/remove Hermes skills.',
    "skill_view": "View a skill's contents.",
    "skills_list": 'List installed skills.',
    "kanban_show": 'Show a kanban card.',
    "kanban_list": 'List kanban cards.',
    "kanban_create": 'Create a kanban card.',
    "kanban_complete": 'Complete a kanban card.',
    "kanban_block": 'Block a kanban card.',
    "kanban_unblock": 'Unblock a kanban card.',
    "kanban_comment": 'Comment on a kanban card.',
    "kanban_link": 'Link kanban cards.',
    "kanban_heartbeat": 'Heartbeat a kanban card.',
    "project_list": 'List Hermes projects.',
    "project_create": 'Create a Hermes project.',
    "project_switch": 'Switch the active project.',
    "ha_get_state": 'Home Assistant: read entity state.',
    "ha_list_entities": 'Home Assistant: list entities.',
    "ha_list_services": 'Home Assistant: list services.',
    "ha_call_service": 'Home Assistant: call a service (act on devices).',
    "feishu_doc_read": 'Feishu: read a document.',
    "feishu_drive_list_comments": 'Feishu: list document comments.',
    "feishu_drive_list_comment_replies": 'Feishu: list comment replies.',
    "feishu_drive_add_comment": 'Feishu: add a comment.',
    "feishu_drive_reply_comment": 'Feishu: reply to a comment.',
    "discord": 'Send Discord messages.',
    "discord_admin": 'Discord administration actions.',
    "yb_query_group_info": 'Messaging: query group info.',
    "yb_query_group_members": 'Messaging: query group members.',
    "yb_search_sticker": 'Messaging: search stickers.',
    "yb_send_dm": 'Messaging: send a direct message.',
    "yb_send_sticker": 'Messaging: send a sticker.',
    "spotify_search": 'Spotify: search.',
    "spotify_devices": 'Spotify: list devices.',
    "spotify_playlists": 'Spotify: list playlists.',
    "spotify_albums": 'Spotify: browse albums.',
    "spotify_library": 'Spotify: browse library.',
    "spotify_playback": 'Spotify: control playback.',
    "spotify_queue": 'Spotify: manage the queue.',
    "meet_status": 'Google Meet: call status.',
    "meet_transcript": 'Google Meet: read transcript.',
    "meet_join": 'Google Meet: join a call.',
    "meet_leave": 'Google Meet: leave a call.',
    "meet_say": 'Google Meet: speak in a call.',
}
TOOL_RISK: dict[str, tuple[str, str]] = {n: (_RISK[n], _RISK_DESC[n]) for n in HERMES_BUILTINS}


def resolve_candidates(tool_name: str) -> list[str]:
    """Candidate policy ids for a Hermes tool name, most specific first.

    ``mcp_<server>_<tool>`` is ambiguous to split, so both the raw name and a
    best-effort ``<server>:<tool>`` form are offered; the engine's first-seen
    match wins. A plain registry name maps to itself.
    """
    if not isinstance(tool_name, str) or not tool_name:
        return []
    if tool_name.startswith("mcp_"):
        rest = tool_name[len("mcp_"):]
        parts = rest.split("_")
        cands = [tool_name]
        for i in range(1, len(parts)):
            server, tool = "_".join(parts[:i]), "_".join(parts[i:])
            if server and tool:
                cands.append(f"{server}:{tool}")
        return cands
    return [tool_name]
